apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/hacbs-contract/enterprise-contract-controller/config/crd?ref=1336dcc40553ef59eda9b681ec96b0b18c06f0dd
- .tekton/

images:
- name: quay.io/redhat-appstudio/enterprise-contract-controller
  newName: quay.io/redhat-appstudio/enterprise-contract-controller
  newTag: 1336dcc40553ef59eda9b681ec96b0b18c06f0dd
